import React, { useContext } from "react";
import Logo from "../../assets/images/logo.png";
import { data, useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import axios from "axios";
import { API } from "../../Host";
import { ThemeContext } from "../../App";

const SubscriptionPlans = () => {
  const {global,setGlobal} = useContext(ThemeContext);
  const navigate = useNavigate();
  const handleSelect = () => {
    navigate("/dashboard");
    toast.success("Welcome To SeekMyCourse!");
  };

  const handlebasicPayment = () => {
    const dataToSend = {
      paymentMethod: "razorpay",
      amount: "999",
      currency: "INR",
      duration: "1 Year",
      plan: "Basic",
      course: 10,
      subtopics: 10,
    };

    onSubmit(dataToSend);
  };

  const handleProPayment = () => {
    const dataToSend = {
      paymentMethod: "razorpay",
      amount: "1999",
      currency: "INR",
      duration: "1 Year",
      plan: "Pro",
      course: 25,
      subtopics: 10,
    };

    onSubmit(dataToSend);
  };

  const onSubmit = async (data) => {
    const { amount, currency, plan, course, subtopics ,duration} = data;
    
    if (!data.paymentMethod) {
      toast.error("Please select a payment method.");
      return;
    }

    try {
      const postURL = API + "/order";
      const res = await axios.post(postURL, {amount:amount*100, currency:currency});
      const order = res.data;
      const options = {
        key: "rzp_live_PwFLUg2b6qe1uU",
        amount: amount,
        currency: currency,
        name: "SeekMyCourse",
        description: "SeekMyCourse Subscription",
        image: "https://hackwittechnologies.com/smc/Logo-1.png",
        order_id: order.id, // This is the order_id generated by Razorpay
        handler: async function (response) {
          const body = {
            ...response,
            uid: localStorage.getItem("user"),
            plan: plan,
          };
          try {
            const validateRes = await axios.post(
              `${API}/order/validate`,
              body,
              {
                headers: {
                  "Content-Type": "application/json",
                },
              }
            );
            const jsonRes = validateRes.data;
            const formData = {
              subscriberId: jsonRes.orderId,
              subscription: jsonRes.paymentId,
              user: localStorage.getItem("user"),
              plan: plan,
              amount: amount,
              method: "razorpay",
              course: course,
              tax: 0,
              subtopics: subtopics,
              duration: duration
            }
            const response = await axios.post(
              `${API}/api/usersubscription`,
              formData
            );
            if (response.status === 200) {
              localStorage.setItem("type", plan);
              const dataToSend = {
                user: localStorage.getItem("user"),
                count: course,
              };
              const response = await axios.post(
                `${API}/api/countplan`,
                dataToSend
              );
            }
              const formDatanotify ={
                user:localStorage.getItem("user"),
                subject:` Subscription Renewal`,
                description:`Your subscription has been renewed. Enjoy uninterrupted access to Pick My Course.`
              }
              await axios.post(`${API}/api/notify`,formDatanotify)
              setGlobal(!global)
            

            navigate("/dashboard");
            toast.success("Payment successful! Subscription activated.");
          } catch (validateError) {
            console.error("Validation error:", validateError);
          }
        },
        prefill: {
          name: 'rk',
          email: 'rdkumar881@gmail.com',
          contact: "0000000000",
        },
        notes: {
          address: "Razorpay Corporate Office",
        },
        theme: {
          color: "#3399cc",
        },
      };

      var rzp1 = new window.Razorpay(options);
      rzp1.on("payment.failed", function (response) {
        toast.error("Payment failed");
      });

      rzp1.open();
    } catch (error) {
      console.error("Error starting Razorpay:", error);
      toast.error("Failed to initiate payment. Please try again.");
    }
  };
  return (
    <>
      <div className="h-screen font-poppins bg-darkgray py-4 overflow-auto">
        <p className="flex  justify-center  py-4 mb-3">
          <img src={Logo} alt="logo Image" className="w-1/4"  />
        </p>

        <div className="flex lg:flex-row md:flex-row flex-col justify-center  gap-6 text-white lg:h-9/12 md:h-9/12 lg:mx-0 md:mx-0 mx-6 ">
          <div className=" bg-darkgray border-2 border-gray-100 rounded-4xl  shadow-md p-4 h-auto ">
            <h2 className="text-teal-400 text-2xl font-medium m-1.5">
              Starter
            </h2>
            <div className="grid  items-center justify-center ">
              <p className="text-4xl text-center text-teal-400 font-semibold mt-4">
                FREE
              </p>
              <button
                onClick={handleSelect}
                className="bg-teal-400 cursor-pointer text-black text-center font-medium  py-1.5 w-36 rounded-md mt-6 mx-auto mb-6"
              >
                Select
              </button>

              <ul className="space-y-2 text-base font-light mt-2 ">
                <li>Generate 1 Free Course</li>
                <li>Theory & Image Course</li>
                <li>Up to 05 Subtopics</li>
                <li>AI Tutor for doubt solving</li>
              </ul>
            </div>
          </div>

          <div className=" bg-teal-400 text-black rounded-4xl  shadow-md p-4">
            <h2 className="text-black text-2xl font-medium m-2">Basic</h2>
            <div className="grid  items-center justify-center ">
              <p className="text-3xl text-center font-semibold">
                ₹999 <span className="text-xl ">/ Year</span>
              </p>
              <p className="text-lg text-center my-2">Billed Annually</p>
              <p
                onClick={handlebasicPayment}
                className="bg-darkgray text-center cursor-pointer text-white font-medium py-1.5 w-36 mx-auto rounded-md "
              >
                Select
              </p>
              <ul className="space-y-2 text-base font-medium mt-7">
                <li>Generate 10 Course / Year</li>
                <li>Theory & Image Course</li>
                <li>Theory & Video Course</li>
                <li>Up to 10 Subtopics</li>
                <li>AI Tutor for doubt solving</li>
                <li>Create / Join Study Groups</li>
                <li>Export Course as PDF</li>
              </ul>
            </div>
          </div>
          <div className="  bg-darkgray border border-gray-100 rounded-4xl shadow-md p-3">
            <h2 className="text-teal-400 text-2xl font-medium m-2">Pro</h2>
            <div className="grid  items-center justify-center ">
              <p className="text-3xl  text-center text-teal-400 font-semibold">
                ₹ 1999 <span className="text-xl">/ Year</span>
              </p>
              <p className="text-lg text-center my-2 ">Billed Annually</p>
              <p
                onClick={handleProPayment}
                className="bg-teal-400 text-center cursor-pointer text-black font-medium py-1.5 w-36 mx-auto rounded-md mb-6"
              >
                Select
              </p>
              <ul className="space-y-2 text-base font-light mt-2">
                <li>Generate 25 Course / Year</li>
                <li>Theory & Image Course</li>
                <li>Theory & Video Course</li>
                <li>Up to 10 Subtopics</li>
                <li>AI Tutor for doubt solving</li>
                <li>Create / Join Study Groups</li>
                <li>Export Course as PDF</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default SubscriptionPlans;
